<?php include 'koneksi.php'; ?>
<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profil - SMAN 1 Bengkalis</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&family=Roboto:wght@400;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link rel="stylesheet" href="css/style.css?v=2">
</head>
<body>
    <div class="top-bar"><div class="container"><div class="top-bar-left"><a href="#" class="top-bar-item"><i class="fas fa-calendar-alt"></i><span>Senin - Jumat: 07.00 - 15.00 WIB</span></a></div><div class="top-bar-right"><a href="tel:+62766123456" class="top-bar-item"><i class="fas fa-phone"></i> (0766) 21234</a><a href="mailto:info@sman1bengkalis.sch.id" class="top-bar-item"><i class="fas fa-envelope"></i> info@sman1bengkalis.sch.id</a><div class="top-bar-social"><a href="#"><i class="fab fa-facebook-f"></i></a><a href="#"><i class="fab fa-instagram"></i></a><a href="#"><i class="fab fa-youtube"></i></a></div></div></div></div>
    <header class="header" id="header"><div class="container"><a href="index.php" class="logo"><div class="logo-icon"><i class="fas fa-graduation-cap"></i></div><div class="logo-text"><h1>SMAN 1 Bengkalis</h1><span>Unggul dalam Prestasi</span></div></a><nav class="nav" id="nav"><ul class="nav-menu" id="navMenu"><li class="nav-item"><a href="index.php" class="nav-link">BERANDA</a></li><li class="nav-item has-dropdown active"><a href="#" class="nav-link">PROFIL <i class="fas fa-chevron-down"></i></a><ul class="dropdown-menu"><li><a href="profile.php">Sambutan Kepala Sekolah</a></li><li><a href="karyawan.php">Guru & Staff</a></li></ul></li><li class="nav-item has-dropdown"><a href="#" class="nav-link">KESISWAAN <i class="fas fa-chevron-down"></i></a><ul class="dropdown-menu"><li><a href="ekstrakurikuler.php">Ekstrakurikuler</a></li><li><a href="prestasi.php">Prestasi Siswa</a></li></ul></li><li class="nav-item has-dropdown"><a href="#" class="nav-link">GALERI <i class="fas fa-chevron-down"></i></a><ul class="dropdown-menu"><li><a href="foto.php">Foto</a></li></ul></li><li class="nav-item"><a href="news.php" class="nav-link">BERITA</a></li><li class="nav-item"><a href="contact.php" class="nav-link">KONTAK</a></li></ul><button class="search-btn" id="searchBtn"><i class="fas fa-search"></i></button><button class="nav-toggle" id="navToggle"><span></span><span></span><span></span></button></nav></div></header>
    <section style="background: linear-gradient(135deg, rgba(0,64,41,0.9), rgba(0,64,41,0.7)), url('https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1600'); background-size: cover; padding: 8rem 0; text-align: center; color: white;"><div class="container"><h1 style="font-size: 4rem; margin-bottom: 1rem;">Profil Sekolah</h1><p style="font-size: 1.8rem; opacity: 0.9;">Mengenal lebih dekat SMAN 1 Bengkalis</p></div></section>
    <section class="welcome-section" id="welcome"><div class="container"><div class="section-header"><h2>Kata Sambutan</h2><p>Kepala Sekolah SMAN 1 Bengkalis</p><div class="divider"></div></div><div class="welcome-grid"><div class="welcome-image"><img src="https://images.unsplash.com/photo-1560250097-0b93528c311a?w=400&h=500&fit=crop" alt="Kepala Sekolah"><div class="welcome-badge"><i class="fas fa-quote-left"></i></div></div><div class="welcome-content"><h3>Dra. Mairustuti, M.Pd</h3><h4>Kepala Sekolah</h4><div class="welcome-text"><p>Assalamu'alaikum Warahmatullahi Wabarakatuh,</p><p>Puji syukur kita panjatkan kehadirat Allah SWT. Website SMAN 1 Bengkalis hadir sebagai media informasi dan komunikasi. Kami berkomitmen meningkatkan kualitas pendidikan dan menghasilkan lulusan yang unggul dalam akademik dan berkarakter mulia.</p><p>Wassalamu'alaikum Warahmatullahi Wabarakatuh.</p></div></div></div></div></section>
    <section class="programs-section" style="background: var(--color-gray-100);"><div class="container"><div class="section-header"><h2>Visi & Misi</h2><p>Landasan pendidikan SMAN 1 Bengkalis</p><div class="divider"></div></div><div class="programs-grid" style="grid-template-columns: repeat(2, 1fr);"><div class="program-card"><div class="program-icon"><i class="fas fa-eye"></i></div><h4>Visi</h4><p>"Terwujudnya lembaga diklat yang menghasilkan SDM unggul, berimtaq, berkarakter dan berlingkungan hidup di era revolusi industri 4.0"</p></div><div class="program-card"><div class="program-icon"><i class="fas fa-bullseye"></i></div><h4>Misi</h4><p>Mewujudkan SDM yang berimtaq, profesional, kreatif, inovatif, mandiri, berakhlak mulia, dan peka terhadap lingkungan.</p></div></div></div></section>
    <section class="stats-section"><div class="container"><div class="stats-grid"><div class="stat-item"><div class="stat-number" data-count="1250">0</div><div class="stat-label">Siswa Aktif</div></div><div class="stat-item"><div class="stat-number" data-count="85">0</div><div class="stat-label">Guru & Staff</div></div><div class="stat-item"><div class="stat-number" data-count="25">0</div><div class="stat-label">Ekstrakurikuler</div></div><div class="stat-item highlight"><div class="stat-number" data-count="150">0</div><div class="stat-label">Prestasi</div></div></div></div></section>
    <footer class="footer"><div class="footer-main"><div class="container"><div class="footer-grid"><div class="footer-col footer-about"><div class="footer-logo"><div class="logo-icon"><i class="fas fa-graduation-cap"></i></div><div class="logo-text"><h3>SMAN 1 Bengkalis</h3><span>Unggul dalam Prestasi</span></div></div><p>Sekolah menengah atas negeri yang berkomitmen mencetak generasi unggul dan berprestasi.</p></div><div class="footer-col"><h4>Link Cepat</h4><ul class="footer-links"><li><a href="index.php">Beranda</a></li><li><a href="profile.php">Profil</a></li><li><a href="news.php">Berita</a></li><li><a href="contact.php">Kontak</a></li></ul></div><div class="footer-col"><h4>Kontak</h4><ul class="footer-contact"><li><i class="fas fa-map-marker-alt"></i><span>Jl. Lembaga, Senggoro</span></li><li><i class="fas fa-phone"></i><span>(0766) 21234</span></li></ul></div></div></div></div><div class="footer-bottom"><div class="container"><div class="footer-bottom-content"><p>&copy; 2025 SMAN 1 Bengkalis.</p></div></div></div></footer>
    <button class="back-to-top" id="backToTop"><i class="fas fa-chevron-up"></i></button>
    <script src="js/main.js?v=2"></script>
    <?php include 'includes/chatbot_widget.php'; ?>
</body>
</html>
